spring:
  jpa:
    hibernate:
      # For local development: create schema at startup and drop on shutdown.
      # Alternatives: 'create' (create once), 'update' (migrate schema — use with caution).
      ddl-auto: create-drop
  datasource:
    # Optional: allow overriding host/port for dev via env vars
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/overlook_hotel
    username: ${DB_USER:overlook_user}
    password: ${DB_PASSWORD:overlook_pass}

# In dev, use a less strict JWT secret (still keep secure in shared environments)
app:
  jwt:
    secret: ${JWT_SECRET:dev_change_me}
